global using NitroxClient.Helpers;
global using NitroxClient.Extensions;
global using Nitrox.Model.Extensions;
global using Nitrox.Model.Logger;
global using Nitrox.Model.Helper;
global using Nitrox.Model.Subnautica.Extensions;
global using Task = System.Threading.Tasks.Task;
global using Mathf = Nitrox.Model.Helper.Mathf;
global using UnityMathf = UnityEngine.Mathf;
global using static NitroxClient.GlobalStatic;
global using static UnityEngine.Object;
