namespace NitroxServer.GameLogic.Entities.Spawning;

/// <summary>
/// Controls how entites are loaded in the world.
/// </summary>
public enum SpawnMode
{
    /// <summary>
    /// Loads entities while the player is moving around the world.  Can cause visibly slower batch load times but saves on initial file size. Respects the world seed.
    /// </summary>
    STREAMING,

    /// <summary>
    /// Loops through all batches to load entities at server start up time.  Can take a very long time to load.  Respects the world seed.
    /// </summary>
    UPFRONT,


    /// <summary>
    /// Uses a pre-baked entity file generated by the Nitrox team.  Instantly loads known entities into memory.  Skips the need for resource parsing and does not respect the world seed. 
    /// </summary>
    BAKED
}
