blank_issues_enabled: false
contact_links:
- name: Nitrox Discord server
  url: https://discord.com/invite/E8B4X9s
  about: Please ask here for help if you have problems with setting up or using Nitrox.
