name: Package Nitrox for Release

on:
  release:
    types: [published]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - runtime: linux-x64
            flatpak-arch: x86_64
          - runtime: linux-arm64
            flatpak-arch: aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build Nitrox Launcher (Self-Contained)
        run: |
          dotnet restore Nitrox.Launcher/Nitrox.Launcher.csproj
          dotnet publish Nitrox.Launcher/Nitrox.Launcher.csproj -c Release -r ${{ matrix.runtime }} --self-contained

      - name: Update manifest for arch
        run: |
          sed -i 's|linux-x64|${{ matrix.runtime }}|g' NitroxPackaging/com.subnauticanitrox.Nitrox.json

      - name: Install Flatpak tools
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean --repo=repo --arch=${{ matrix.flatpak-arch }} build-dir NitroxPackaging/com.subnauticanitrox.Nitrox.json

      - name: Make AppImage
        run: |
          APPDIR=AppDir
          mkdir -p "$APPDIR/usr/bin"
          cp -r Nitrox.Launcher/bin/Release/net9.0/${{ matrix.runtime }}/publish/* "$APPDIR/usr/bin/"
          mkdir -p "$APPDIR/usr/share/applications"
          echo "[Desktop Entry]\nName=Nitrox Launcher\nExec=NitroxLauncher\nIcon=nitrox\nType=Application\nCategories=Game;" > "$APPDIR/usr/share/applications/nitrox.desktop"
          mkdir -p "$APPDIR/usr/share/icons/hicolor/256x256/apps"
          cp Nitrox.Launcher/Assets/Images/subnautica-icon.png "$APPDIR/usr/share/icons/hicolor/256x256/apps/nitrox.png"
          if [ ! -f appimagetool ]; then
            wget https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage -O appimagetool
            chmod +x appimagetool
          fi
          ./appimagetool "$APPDIR" "NitroxLauncher-${{ matrix.runtime }}.AppImage"

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: Nitrox-Flatpak-${{ matrix.runtime }}
          path: repo

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Nitrox-AppImage-${{ matrix.runtime }}
          path: NitroxLauncher-${{ matrix.runtime }}.AppImage
