global using System;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Nitrox.Model;
global using Nitrox.Model.Configuration;
global using Nitrox.Model.Extensions;
global using Nitrox.Model.Helper;
global using Nitrox.Model.Logger;
global using Nitrox.Model.Packets;
global using Nitrox.Model.Subnautica.Packets;
global using Nitrox.Model.Subnautica.Extensions;
global using Nitrox.Server.Subnautica.Extensions;
global using ZLogger;
global using LogLevel = Microsoft.Extensions.Logging.LogLevel;
