global using System.Threading.Tasks;
global using NitroxModel;
global using Microsoft.Extensions.Logging;
global using NitroxModel.Networking;
global using NitroxServer.Extensions;
global using Nitrox.Server.Subnautica.Extensions;
global using Nitrox.Server.Subnautica.Extensions.Dto;
global using Stopwatch = System.Diagnostics.Stopwatch;
global using ZLogger;
global using LogLevel = Microsoft.Extensions.Logging.LogLevel;
