### YamlMime:ManagedReference
items:
- uid: NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable
  commentId: T:NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable
  id: NitroxConfig`1.UpdateDiposable
  parent: NitroxModel.Serialization
  children:
  - NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.#ctor(NitroxModel.Serialization.NitroxConfig{`0},System.String)
  - NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.Dispose
  langs:
  - csharp
  - vb
  name: NitroxConfig<T>.UpdateDiposable
  nameWithType: NitroxConfig<T>.UpdateDiposable
  fullName: NitroxModel.Serialization.NitroxConfig<T>.UpdateDiposable
  type: Struct
  source:
    remote:
      path: NitroxModel/Serialization/NitroxConfig.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: UpdateDiposable
    path: ../NitroxModel/Serialization/NitroxConfig.cs
    startLine: 237
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Serialization
  syntax:
    content: 'public struct NitroxConfig<T>.UpdateDiposable : IDisposable'
    content.vb: Public Structure NitroxConfig(Of T).UpdateDiposable Implements IDisposable
  implements:
  - System.IDisposable
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetType
  nameWithType.vb: NitroxConfig(Of T).UpdateDiposable
  fullName.vb: NitroxModel.Serialization.NitroxConfig(Of T).UpdateDiposable
  name.vb: NitroxConfig(Of T).UpdateDiposable
- uid: NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.#ctor(NitroxModel.Serialization.NitroxConfig{`0},System.String)
  commentId: M:NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.#ctor(NitroxModel.Serialization.NitroxConfig{`0},System.String)
  id: '#ctor(NitroxModel.Serialization.NitroxConfig{`0},System.String)'
  parent: NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable
  langs:
  - csharp
  - vb
  name: UpdateDiposable(NitroxConfig<T>, string)
  nameWithType: NitroxConfig<T>.UpdateDiposable.UpdateDiposable(NitroxConfig<T>, string)
  fullName: NitroxModel.Serialization.NitroxConfig<T>.UpdateDiposable.UpdateDiposable(NitroxModel.Serialization.NitroxConfig<T>, string)
  type: Constructor
  source:
    remote:
      path: NitroxModel/Serialization/NitroxConfig.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: .ctor
    path: ../NitroxModel/Serialization/NitroxConfig.cs
    startLine: 242
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Serialization
  syntax:
    content: public UpdateDiposable(NitroxConfig<T> config, string saveDir)
    parameters:
    - id: config
      type: NitroxModel.Serialization.NitroxConfig`1
    - id: saveDir
      type: System.String
    content.vb: Public Sub New(config As NitroxConfig(Of T), saveDir As String)
  overload: NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.#ctor*
  nameWithType.vb: NitroxConfig(Of T).UpdateDiposable.New(NitroxConfig(Of T), String)
  fullName.vb: NitroxModel.Serialization.NitroxConfig(Of T).UpdateDiposable.New(NitroxModel.Serialization.NitroxConfig(Of T), String)
  name.vb: New(NitroxConfig(Of T), String)
- uid: NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.Dispose
  commentId: M:NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.Dispose
  id: Dispose
  parent: NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable
  langs:
  - csharp
  - vb
  name: Dispose()
  nameWithType: NitroxConfig<T>.UpdateDiposable.Dispose()
  fullName: NitroxModel.Serialization.NitroxConfig<T>.UpdateDiposable.Dispose()
  type: Method
  source:
    remote:
      path: NitroxModel/Serialization/NitroxConfig.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: Dispose
    path: ../NitroxModel/Serialization/NitroxConfig.cs
    startLine: 249
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Serialization
  summary: Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
  example: []
  syntax:
    content: public void Dispose()
    content.vb: Public Sub Dispose()
  overload: NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.Dispose*
  implements:
  - System.IDisposable.Dispose
  nameWithType.vb: NitroxConfig(Of T).UpdateDiposable.Dispose()
  fullName.vb: NitroxModel.Serialization.NitroxConfig(Of T).UpdateDiposable.Dispose()
references:
- uid: NitroxModel.Serialization
  commentId: N:NitroxModel.Serialization
  href: NitroxModel.html
  name: NitroxModel.Serialization
  nameWithType: NitroxModel.Serialization
  fullName: NitroxModel.Serialization
  spec.csharp:
  - uid: NitroxModel
    name: NitroxModel
    href: NitroxModel.html
  - name: .
  - uid: NitroxModel.Serialization
    name: Serialization
    href: NitroxModel.Serialization.html
  spec.vb:
  - uid: NitroxModel
    name: NitroxModel
    href: NitroxModel.html
  - name: .
  - uid: NitroxModel.Serialization
    name: Serialization
    href: NitroxModel.Serialization.html
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.#ctor*
  commentId: Overload:NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.#ctor
  href: NitroxModel.Serialization.NitroxConfig-1.UpdateDiposable.-ctor.html#NitroxModel_Serialization_NitroxConfig_1_UpdateDiposable__ctor_NitroxModel_Serialization_NitroxConfig__0__System_String_
  name: UpdateDiposable
  nameWithType: NitroxConfig<T>.UpdateDiposable.UpdateDiposable
  fullName: NitroxModel.Serialization.NitroxConfig<T>.UpdateDiposable.UpdateDiposable
  nameWithType.vb: NitroxConfig(Of T).UpdateDiposable.New
  fullName.vb: NitroxModel.Serialization.NitroxConfig(Of T).UpdateDiposable.New
  name.vb: New
- uid: NitroxModel.Serialization.NitroxConfig`1
  commentId: T:NitroxModel.Serialization.NitroxConfig`1
  parent: NitroxModel.Serialization
  href: NitroxModel.Serialization.NitroxConfig-1.html
  name: NitroxConfig<T>
  nameWithType: NitroxConfig<T>
  fullName: NitroxModel.Serialization.NitroxConfig<T>
  nameWithType.vb: NitroxConfig(Of T)
  fullName.vb: NitroxModel.Serialization.NitroxConfig(Of T)
  name.vb: NitroxConfig(Of T)
  spec.csharp:
  - uid: NitroxModel.Serialization.NitroxConfig`1
    name: NitroxConfig
    href: NitroxModel.Serialization.NitroxConfig-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: NitroxModel.Serialization.NitroxConfig`1
    name: NitroxConfig
    href: NitroxModel.Serialization.NitroxConfig-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.Dispose*
  commentId: Overload:NitroxModel.Serialization.NitroxConfig`1.UpdateDiposable.Dispose
  href: NitroxModel.Serialization.NitroxConfig-1.UpdateDiposable.Dispose.html#NitroxModel_Serialization_NitroxConfig_1_UpdateDiposable_Dispose
  name: Dispose
  nameWithType: NitroxConfig<T>.UpdateDiposable.Dispose
  fullName: NitroxModel.Serialization.NitroxConfig<T>.UpdateDiposable.Dispose
  nameWithType.vb: NitroxConfig(Of T).UpdateDiposable.Dispose
  fullName.vb: NitroxModel.Serialization.NitroxConfig(Of T).UpdateDiposable.Dispose
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
memberLayout: SeparatePages
