### YamlMime:ManagedReference
items:
- uid: NitroxModel.MultiplayerSession.PlayerSettings
  commentId: T:NitroxModel.MultiplayerSession.PlayerSettings
  id: PlayerSettings
  parent: NitroxModel.MultiplayerSession
  children:
  - NitroxModel.MultiplayerSession.PlayerSettings.#ctor(NitroxModel.DataStructures.Unity.NitroxColor)
  - NitroxModel.MultiplayerSession.PlayerSettings.PlayerColor
  - NitroxModel.MultiplayerSession.PlayerSettings.ToString
  langs:
  - csharp
  - vb
  name: PlayerSettings
  nameWithType: PlayerSettings
  fullName: NitroxModel.MultiplayerSession.PlayerSettings
  type: Class
  source:
    remote:
      path: NitroxModel/MultiplayerSession/PlayerSettings.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: PlayerSettings
    path: ../NitroxModel/MultiplayerSession/PlayerSettings.cs
    startLine: 5
  assemblies:
  - NitroxModel
  namespace: NitroxModel.MultiplayerSession
  syntax:
    content: >-
      [Serializable]

      public class PlayerSettings
    content.vb: >-
      <Serializable>

      Public Class PlayerSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: NitroxModel.MultiplayerSession.PlayerSettings.PlayerColor
  commentId: P:NitroxModel.MultiplayerSession.PlayerSettings.PlayerColor
  id: PlayerColor
  parent: NitroxModel.MultiplayerSession.PlayerSettings
  langs:
  - csharp
  - vb
  name: PlayerColor
  nameWithType: PlayerSettings.PlayerColor
  fullName: NitroxModel.MultiplayerSession.PlayerSettings.PlayerColor
  type: Property
  source:
    remote:
      path: NitroxModel/MultiplayerSession/PlayerSettings.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: PlayerColor
    path: ../NitroxModel/MultiplayerSession/PlayerSettings.cs
    startLine: 8
  assemblies:
  - NitroxModel
  namespace: NitroxModel.MultiplayerSession
  syntax:
    content: public NitroxColor PlayerColor { get; }
    parameters: []
    return:
      type: NitroxModel.DataStructures.Unity.NitroxColor
    content.vb: Public ReadOnly Property PlayerColor As NitroxColor
  overload: NitroxModel.MultiplayerSession.PlayerSettings.PlayerColor*
- uid: NitroxModel.MultiplayerSession.PlayerSettings.#ctor(NitroxModel.DataStructures.Unity.NitroxColor)
  commentId: M:NitroxModel.MultiplayerSession.PlayerSettings.#ctor(NitroxModel.DataStructures.Unity.NitroxColor)
  id: '#ctor(NitroxModel.DataStructures.Unity.NitroxColor)'
  parent: NitroxModel.MultiplayerSession.PlayerSettings
  langs:
  - csharp
  - vb
  name: PlayerSettings(NitroxColor)
  nameWithType: PlayerSettings.PlayerSettings(NitroxColor)
  fullName: NitroxModel.MultiplayerSession.PlayerSettings.PlayerSettings(NitroxModel.DataStructures.Unity.NitroxColor)
  type: Constructor
  source:
    remote:
      path: NitroxModel/MultiplayerSession/PlayerSettings.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: .ctor
    path: ../NitroxModel/MultiplayerSession/PlayerSettings.cs
    startLine: 10
  assemblies:
  - NitroxModel
  namespace: NitroxModel.MultiplayerSession
  syntax:
    content: public PlayerSettings(NitroxColor playerColor)
    parameters:
    - id: playerColor
      type: NitroxModel.DataStructures.Unity.NitroxColor
    content.vb: Public Sub New(playerColor As NitroxColor)
  overload: NitroxModel.MultiplayerSession.PlayerSettings.#ctor*
  nameWithType.vb: PlayerSettings.New(NitroxColor)
  fullName.vb: NitroxModel.MultiplayerSession.PlayerSettings.New(NitroxModel.DataStructures.Unity.NitroxColor)
  name.vb: New(NitroxColor)
- uid: NitroxModel.MultiplayerSession.PlayerSettings.ToString
  commentId: M:NitroxModel.MultiplayerSession.PlayerSettings.ToString
  id: ToString
  parent: NitroxModel.MultiplayerSession.PlayerSettings
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: PlayerSettings.ToString()
  fullName: NitroxModel.MultiplayerSession.PlayerSettings.ToString()
  type: Method
  source:
    remote:
      path: NitroxModel/MultiplayerSession/PlayerSettings.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: ToString
    path: ../NitroxModel/MultiplayerSession/PlayerSettings.cs
    startLine: 15
  assemblies:
  - NitroxModel
  namespace: NitroxModel.MultiplayerSession
  summary: Returns a string that represents the current object.
  example: []
  syntax:
    content: public override string ToString()
    return:
      type: System.String
      description: A string that represents the current object.
    content.vb: Public Overrides Function ToString() As String
  overridden: System.Object.ToString
  overload: NitroxModel.MultiplayerSession.PlayerSettings.ToString*
references:
- uid: NitroxModel.MultiplayerSession
  commentId: N:NitroxModel.MultiplayerSession
  href: NitroxModel.html
  name: NitroxModel.MultiplayerSession
  nameWithType: NitroxModel.MultiplayerSession
  fullName: NitroxModel.MultiplayerSession
  spec.csharp:
  - uid: NitroxModel
    name: NitroxModel
    href: NitroxModel.html
  - name: .
  - uid: NitroxModel.MultiplayerSession
    name: MultiplayerSession
    href: NitroxModel.MultiplayerSession.html
  spec.vb:
  - uid: NitroxModel
    name: NitroxModel
    href: NitroxModel.html
  - name: .
  - uid: NitroxModel.MultiplayerSession
    name: MultiplayerSession
    href: NitroxModel.MultiplayerSession.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: NitroxModel.MultiplayerSession.PlayerSettings.PlayerColor*
  commentId: Overload:NitroxModel.MultiplayerSession.PlayerSettings.PlayerColor
  href: NitroxModel.MultiplayerSession.PlayerSettings.PlayerColor.html#NitroxModel_MultiplayerSession_PlayerSettings_PlayerColor
  name: PlayerColor
  nameWithType: PlayerSettings.PlayerColor
  fullName: NitroxModel.MultiplayerSession.PlayerSettings.PlayerColor
- uid: NitroxModel.DataStructures.Unity.NitroxColor
  commentId: T:NitroxModel.DataStructures.Unity.NitroxColor
  parent: NitroxModel.DataStructures.Unity
  href: NitroxModel.DataStructures.Unity.NitroxColor.html
  name: NitroxColor
  nameWithType: NitroxColor
  fullName: NitroxModel.DataStructures.Unity.NitroxColor
- uid: NitroxModel.DataStructures.Unity
  commentId: N:NitroxModel.DataStructures.Unity
  href: NitroxModel.html
  name: NitroxModel.DataStructures.Unity
  nameWithType: NitroxModel.DataStructures.Unity
  fullName: NitroxModel.DataStructures.Unity
  spec.csharp:
  - uid: NitroxModel
    name: NitroxModel
    href: NitroxModel.html
  - name: .
  - uid: NitroxModel.DataStructures
    name: DataStructures
    href: NitroxModel.DataStructures.html
  - name: .
  - uid: NitroxModel.DataStructures.Unity
    name: Unity
    href: NitroxModel.DataStructures.Unity.html
  spec.vb:
  - uid: NitroxModel
    name: NitroxModel
    href: NitroxModel.html
  - name: .
  - uid: NitroxModel.DataStructures
    name: DataStructures
    href: NitroxModel.DataStructures.html
  - name: .
  - uid: NitroxModel.DataStructures.Unity
    name: Unity
    href: NitroxModel.DataStructures.Unity.html
- uid: NitroxModel.MultiplayerSession.PlayerSettings.#ctor*
  commentId: Overload:NitroxModel.MultiplayerSession.PlayerSettings.#ctor
  href: NitroxModel.MultiplayerSession.PlayerSettings.-ctor.html#NitroxModel_MultiplayerSession_PlayerSettings__ctor_NitroxModel_DataStructures_Unity_NitroxColor_
  name: PlayerSettings
  nameWithType: PlayerSettings.PlayerSettings
  fullName: NitroxModel.MultiplayerSession.PlayerSettings.PlayerSettings
  nameWithType.vb: PlayerSettings.New
  fullName.vb: NitroxModel.MultiplayerSession.PlayerSettings.New
  name.vb: New
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: NitroxModel.MultiplayerSession.PlayerSettings.ToString*
  commentId: Overload:NitroxModel.MultiplayerSession.PlayerSettings.ToString
  href: NitroxModel.MultiplayerSession.PlayerSettings.ToString.html#NitroxModel_MultiplayerSession_PlayerSettings_ToString
  name: ToString
  nameWithType: PlayerSettings.ToString
  fullName: NitroxModel.MultiplayerSession.PlayerSettings.ToString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
memberLayout: SeparatePages
