### YamlMime:ManagedReference
items:
- uid: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  commentId: T:NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  id: ProcessEnvironmentBlock64
  parent: NitroxModel.Platforms.OS.Windows.Internal
  children:
  - NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.BeingDebugged
  - NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.ImageBaseAddress
  - NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.LdrData
  - NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.ProcessParameters
  - NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved1
  - NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved2
  - NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved3
  langs:
  - csharp
  - vb
  name: ProcessEnvironmentBlock64
  nameWithType: ProcessEnvironmentBlock64
  fullName: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  type: Struct
  source:
    remote:
      path: NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: ProcessEnvironmentBlock64
    path: ../NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
    startLine: 10
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Platforms.OS.Windows.Internal
  summary: >-
    PEB structure in a used by Windows in 64-bit processes.

    See full structure here:

    https://ntopcode.wordpress.com/2018/02/26/anatomy-of-the-process-environment-block-peb-windows-internals/
  example: []
  syntax:
    content: public struct ProcessEnvironmentBlock64
    content.vb: Public Structure ProcessEnvironmentBlock64
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetType
- uid: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved1
  commentId: F:NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved1
  id: Reserved1
  parent: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  langs:
  - csharp
  - vb
  name: Reserved1
  nameWithType: ProcessEnvironmentBlock64.Reserved1
  fullName: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved1
  type: Field
  source:
    remote:
      path: NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: Reserved1
    path: ../NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
    startLine: 14
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Platforms.OS.Windows.Internal
  syntax:
    content: public byte Reserved1
    return:
      type: System.Byte
    content.vb: Public Reserved1 As Byte
- uid: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved2
  commentId: F:NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved2
  id: Reserved2
  parent: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  langs:
  - csharp
  - vb
  name: Reserved2
  nameWithType: ProcessEnvironmentBlock64.Reserved2
  fullName: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved2
  type: Field
  source:
    remote:
      path: NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: Reserved2
    path: ../NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
    startLine: 16
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Platforms.OS.Windows.Internal
  syntax:
    content: public byte Reserved2
    return:
      type: System.Byte
    content.vb: Public Reserved2 As Byte
- uid: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.BeingDebugged
  commentId: F:NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.BeingDebugged
  id: BeingDebugged
  parent: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  langs:
  - csharp
  - vb
  name: BeingDebugged
  nameWithType: ProcessEnvironmentBlock64.BeingDebugged
  fullName: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.BeingDebugged
  type: Field
  source:
    remote:
      path: NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: BeingDebugged
    path: ../NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
    startLine: 18
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Platforms.OS.Windows.Internal
  syntax:
    content: public byte BeingDebugged
    return:
      type: System.Byte
    content.vb: Public BeingDebugged As Byte
- uid: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved3
  commentId: F:NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved3
  id: Reserved3
  parent: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  langs:
  - csharp
  - vb
  name: Reserved3
  nameWithType: ProcessEnvironmentBlock64.Reserved3
  fullName: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.Reserved3
  type: Field
  source:
    remote:
      path: NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: Reserved3
    path: ../NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
    startLine: 20
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Platforms.OS.Windows.Internal
  syntax:
    content: public byte Reserved3
    return:
      type: System.Byte
    content.vb: Public Reserved3 As Byte
- uid: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.ImageBaseAddress
  commentId: F:NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.ImageBaseAddress
  id: ImageBaseAddress
  parent: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  langs:
  - csharp
  - vb
  name: ImageBaseAddress
  nameWithType: ProcessEnvironmentBlock64.ImageBaseAddress
  fullName: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.ImageBaseAddress
  type: Field
  source:
    remote:
      path: NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: ImageBaseAddress
    path: ../NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
    startLine: 23
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Platforms.OS.Windows.Internal
  syntax:
    content: public IntPtr ImageBaseAddress
    return:
      type: System.IntPtr
    content.vb: Public ImageBaseAddress As IntPtr
- uid: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.LdrData
  commentId: F:NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.LdrData
  id: LdrData
  parent: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  langs:
  - csharp
  - vb
  name: LdrData
  nameWithType: ProcessEnvironmentBlock64.LdrData
  fullName: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.LdrData
  type: Field
  source:
    remote:
      path: NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: LdrData
    path: ../NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
    startLine: 29
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Platforms.OS.Windows.Internal
  summary: Ptr to structure <xref href="NitroxModel.Platforms.OS.Windows.Internal.LdrData" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public IntPtr LdrData
    return:
      type: System.IntPtr
    content.vb: Public LdrData As IntPtr
- uid: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.ProcessParameters
  commentId: F:NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.ProcessParameters
  id: ProcessParameters
  parent: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64
  langs:
  - csharp
  - vb
  name: ProcessParameters
  nameWithType: ProcessEnvironmentBlock64.ProcessParameters
  fullName: NitroxModel.Platforms.OS.Windows.Internal.ProcessEnvironmentBlock64.ProcessParameters
  type: Field
  source:
    remote:
      path: NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: ProcessParameters
    path: ../NitroxModel/Platforms/OS/Windows/Internal/ProcessEnvironmentBlock64.cs
    startLine: 32
  assemblies:
  - NitroxModel
  namespace: NitroxModel.Platforms.OS.Windows.Internal
  syntax:
    content: public IntPtr ProcessParameters
    return:
      type: System.IntPtr
    content.vb: Public ProcessParameters As IntPtr
references:
- uid: NitroxModel.Platforms.OS.Windows.Internal
  commentId: N:NitroxModel.Platforms.OS.Windows.Internal
  href: NitroxModel.html
  name: NitroxModel.Platforms.OS.Windows.Internal
  nameWithType: NitroxModel.Platforms.OS.Windows.Internal
  fullName: NitroxModel.Platforms.OS.Windows.Internal
  spec.csharp:
  - uid: NitroxModel
    name: NitroxModel
    href: NitroxModel.html
  - name: .
  - uid: NitroxModel.Platforms
    name: Platforms
    href: NitroxModel.Platforms.html
  - name: .
  - uid: NitroxModel.Platforms.OS
    name: OS
    href: NitroxModel.Platforms.OS.html
  - name: .
  - uid: NitroxModel.Platforms.OS.Windows
    name: Windows
    href: NitroxModel.Platforms.OS.Windows.html
  - name: .
  - uid: NitroxModel.Platforms.OS.Windows.Internal
    name: Internal
    href: NitroxModel.Platforms.OS.Windows.Internal.html
  spec.vb:
  - uid: NitroxModel
    name: NitroxModel
    href: NitroxModel.html
  - name: .
  - uid: NitroxModel.Platforms
    name: Platforms
    href: NitroxModel.Platforms.html
  - name: .
  - uid: NitroxModel.Platforms.OS
    name: OS
    href: NitroxModel.Platforms.OS.html
  - name: .
  - uid: NitroxModel.Platforms.OS.Windows
    name: Windows
    href: NitroxModel.Platforms.OS.Windows.html
  - name: .
  - uid: NitroxModel.Platforms.OS.Windows.Internal
    name: Internal
    href: NitroxModel.Platforms.OS.Windows.Internal.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Byte
  commentId: T:System.Byte
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte
  nameWithType: byte
  fullName: byte
  nameWithType.vb: Byte
  fullName.vb: Byte
  name.vb: Byte
- uid: System.IntPtr
  commentId: T:System.IntPtr
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.intptr
  name: IntPtr
  nameWithType: IntPtr
  fullName: System.IntPtr
- uid: NitroxModel.Platforms.OS.Windows.Internal.LdrData
  commentId: T:NitroxModel.Platforms.OS.Windows.Internal.LdrData
  href: NitroxModel.Platforms.OS.Windows.Internal.LdrData.html
  name: LdrData
  nameWithType: LdrData
  fullName: NitroxModel.Platforms.OS.Windows.Internal.LdrData
memberLayout: SeparatePages
