### YamlMime:ManagedReference
items:
- uid: NitroxClient.GameLogic.Settings.NitroxPrefs
  commentId: T:NitroxClient.GameLogic.Settings.NitroxPrefs
  id: NitroxPrefs
  parent: NitroxClient.GameLogic.Settings
  children:
  - NitroxClient.GameLogic.Settings.NitroxPrefs.ChatUsed
  - NitroxClient.GameLogic.Settings.NitroxPrefs.HideIp
  - NitroxClient.GameLogic.Settings.NitroxPrefs.SafeBuilding
  - NitroxClient.GameLogic.Settings.NitroxPrefs.SafeBuildingLog
  - NitroxClient.GameLogic.Settings.NitroxPrefs.SilenceChat
  langs:
  - csharp
  - vb
  name: NitroxPrefs
  nameWithType: NitroxPrefs
  fullName: NitroxClient.GameLogic.Settings.NitroxPrefs
  type: Class
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxPrefs.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: NitroxPrefs
    path: ../NitroxClient/GameLogic/Settings/NitroxPrefs.cs
    startLine: 5
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: public class NitroxPrefs
    content.vb: Public Class NitroxPrefs
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: NitroxClient.GameLogic.Settings.NitroxPrefs.HideIp
  commentId: F:NitroxClient.GameLogic.Settings.NitroxPrefs.HideIp
  id: HideIp
  parent: NitroxClient.GameLogic.Settings.NitroxPrefs
  langs:
  - csharp
  - vb
  name: HideIp
  nameWithType: NitroxPrefs.HideIp
  fullName: NitroxClient.GameLogic.Settings.NitroxPrefs.HideIp
  type: Field
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxPrefs.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: HideIp
    path: ../NitroxClient/GameLogic/Settings/NitroxPrefs.cs
    startLine: 8
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: public static readonly NitroxPref<bool> HideIp
    return:
      type: NitroxClient.GameLogic.Settings.NitroxPref{System.Boolean}
    content.vb: Public Shared ReadOnly HideIp As NitroxPref(Of Boolean)
- uid: NitroxClient.GameLogic.Settings.NitroxPrefs.SilenceChat
  commentId: F:NitroxClient.GameLogic.Settings.NitroxPrefs.SilenceChat
  id: SilenceChat
  parent: NitroxClient.GameLogic.Settings.NitroxPrefs
  langs:
  - csharp
  - vb
  name: SilenceChat
  nameWithType: NitroxPrefs.SilenceChat
  fullName: NitroxClient.GameLogic.Settings.NitroxPrefs.SilenceChat
  type: Field
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxPrefs.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: SilenceChat
    path: ../NitroxClient/GameLogic/Settings/NitroxPrefs.cs
    startLine: 9
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: public static readonly NitroxPref<bool> SilenceChat
    return:
      type: NitroxClient.GameLogic.Settings.NitroxPref{System.Boolean}
    content.vb: Public Shared ReadOnly SilenceChat As NitroxPref(Of Boolean)
- uid: NitroxClient.GameLogic.Settings.NitroxPrefs.ChatUsed
  commentId: F:NitroxClient.GameLogic.Settings.NitroxPrefs.ChatUsed
  id: ChatUsed
  parent: NitroxClient.GameLogic.Settings.NitroxPrefs
  langs:
  - csharp
  - vb
  name: ChatUsed
  nameWithType: NitroxPrefs.ChatUsed
  fullName: NitroxClient.GameLogic.Settings.NitroxPrefs.ChatUsed
  type: Field
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxPrefs.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: ChatUsed
    path: ../NitroxClient/GameLogic/Settings/NitroxPrefs.cs
    startLine: 10
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: public static readonly NitroxPref<bool> ChatUsed
    return:
      type: NitroxClient.GameLogic.Settings.NitroxPref{System.Boolean}
    content.vb: Public Shared ReadOnly ChatUsed As NitroxPref(Of Boolean)
- uid: NitroxClient.GameLogic.Settings.NitroxPrefs.SafeBuilding
  commentId: F:NitroxClient.GameLogic.Settings.NitroxPrefs.SafeBuilding
  id: SafeBuilding
  parent: NitroxClient.GameLogic.Settings.NitroxPrefs
  langs:
  - csharp
  - vb
  name: SafeBuilding
  nameWithType: NitroxPrefs.SafeBuilding
  fullName: NitroxClient.GameLogic.Settings.NitroxPrefs.SafeBuilding
  type: Field
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxPrefs.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: SafeBuilding
    path: ../NitroxClient/GameLogic/Settings/NitroxPrefs.cs
    startLine: 11
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: public static readonly NitroxPref<bool> SafeBuilding
    return:
      type: NitroxClient.GameLogic.Settings.NitroxPref{System.Boolean}
    content.vb: Public Shared ReadOnly SafeBuilding As NitroxPref(Of Boolean)
- uid: NitroxClient.GameLogic.Settings.NitroxPrefs.SafeBuildingLog
  commentId: F:NitroxClient.GameLogic.Settings.NitroxPrefs.SafeBuildingLog
  id: SafeBuildingLog
  parent: NitroxClient.GameLogic.Settings.NitroxPrefs
  langs:
  - csharp
  - vb
  name: SafeBuildingLog
  nameWithType: NitroxPrefs.SafeBuildingLog
  fullName: NitroxClient.GameLogic.Settings.NitroxPrefs.SafeBuildingLog
  type: Field
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxPrefs.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: SafeBuildingLog
    path: ../NitroxClient/GameLogic/Settings/NitroxPrefs.cs
    startLine: 12
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: public static readonly NitroxPref<bool> SafeBuildingLog
    return:
      type: NitroxClient.GameLogic.Settings.NitroxPref{System.Boolean}
    content.vb: Public Shared ReadOnly SafeBuildingLog As NitroxPref(Of Boolean)
references:
- uid: NitroxClient.GameLogic.Settings
  commentId: N:NitroxClient.GameLogic.Settings
  href: NitroxClient.html
  name: NitroxClient.GameLogic.Settings
  nameWithType: NitroxClient.GameLogic.Settings
  fullName: NitroxClient.GameLogic.Settings
  spec.csharp:
  - uid: NitroxClient
    name: NitroxClient
    href: NitroxClient.html
  - name: .
  - uid: NitroxClient.GameLogic
    name: GameLogic
    href: NitroxClient.GameLogic.html
  - name: .
  - uid: NitroxClient.GameLogic.Settings
    name: Settings
    href: NitroxClient.GameLogic.Settings.html
  spec.vb:
  - uid: NitroxClient
    name: NitroxClient
    href: NitroxClient.html
  - name: .
  - uid: NitroxClient.GameLogic
    name: GameLogic
    href: NitroxClient.GameLogic.html
  - name: .
  - uid: NitroxClient.GameLogic.Settings
    name: Settings
    href: NitroxClient.GameLogic.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: NitroxClient.GameLogic.Settings.NitroxPref{System.Boolean}
  commentId: T:NitroxClient.GameLogic.Settings.NitroxPref{System.Boolean}
  parent: NitroxClient.GameLogic.Settings
  definition: NitroxClient.GameLogic.Settings.NitroxPref`1
  href: NitroxClient.GameLogic.Settings.NitroxPref-1.html
  name: NitroxPref<bool>
  nameWithType: NitroxPref<bool>
  fullName: NitroxClient.GameLogic.Settings.NitroxPref<bool>
  nameWithType.vb: NitroxPref(Of Boolean)
  fullName.vb: NitroxClient.GameLogic.Settings.NitroxPref(Of Boolean)
  name.vb: NitroxPref(Of Boolean)
  spec.csharp:
  - uid: NitroxClient.GameLogic.Settings.NitroxPref`1
    name: NitroxPref
    href: NitroxClient.GameLogic.Settings.NitroxPref-1.html
  - name: <
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '>'
  spec.vb:
  - uid: NitroxClient.GameLogic.Settings.NitroxPref`1
    name: NitroxPref
    href: NitroxClient.GameLogic.Settings.NitroxPref-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
- uid: NitroxClient.GameLogic.Settings.NitroxPref`1
  commentId: T:NitroxClient.GameLogic.Settings.NitroxPref`1
  href: NitroxClient.GameLogic.Settings.NitroxPref-1.html
  name: NitroxPref<T>
  nameWithType: NitroxPref<T>
  fullName: NitroxClient.GameLogic.Settings.NitroxPref<T>
  nameWithType.vb: NitroxPref(Of T)
  fullName.vb: NitroxClient.GameLogic.Settings.NitroxPref(Of T)
  name.vb: NitroxPref(Of T)
  spec.csharp:
  - uid: NitroxClient.GameLogic.Settings.NitroxPref`1
    name: NitroxPref
    href: NitroxClient.GameLogic.Settings.NitroxPref-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: NitroxClient.GameLogic.Settings.NitroxPref`1
    name: NitroxPref
    href: NitroxClient.GameLogic.Settings.NitroxPref-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
memberLayout: SeparatePages
