### YamlMime:ManagedReference
items:
- uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  commentId: T:NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  id: NitroxSettingsManager.SettingType
  parent: NitroxClient.GameLogic.Settings
  children:
  - NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.BUTTON
  - NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.LIST
  - NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.SLIDER
  - NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.TOGGLE
  langs:
  - csharp
  - vb
  name: NitroxSettingsManager.SettingType
  nameWithType: NitroxSettingsManager.SettingType
  fullName: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  type: Enum
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: SettingType
    path: ../NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
    startLine: 127
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: public enum NitroxSettingsManager.SettingType
    content.vb: Public Enum NitroxSettingsManager.SettingType
  extensionMethods:
  - System.Enum.NitroxModel.Extensions.GetAttribute``1
- uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.TOGGLE
  commentId: F:NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.TOGGLE
  id: TOGGLE
  parent: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  langs:
  - csharp
  - vb
  name: TOGGLE
  nameWithType: NitroxSettingsManager.SettingType.TOGGLE
  fullName: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.TOGGLE
  type: Field
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: TOGGLE
    path: ../NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
    startLine: 129
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: TOGGLE = 0
    return:
      type: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
- uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.SLIDER
  commentId: F:NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.SLIDER
  id: SLIDER
  parent: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  langs:
  - csharp
  - vb
  name: SLIDER
  nameWithType: NitroxSettingsManager.SettingType.SLIDER
  fullName: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.SLIDER
  type: Field
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: SLIDER
    path: ../NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
    startLine: 129
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: SLIDER = 1
    return:
      type: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
- uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.LIST
  commentId: F:NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.LIST
  id: LIST
  parent: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  langs:
  - csharp
  - vb
  name: LIST
  nameWithType: NitroxSettingsManager.SettingType.LIST
  fullName: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.LIST
  type: Field
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: LIST
    path: ../NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
    startLine: 129
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: LIST = 2
    return:
      type: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
- uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.BUTTON
  commentId: F:NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.BUTTON
  id: BUTTON
  parent: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  langs:
  - csharp
  - vb
  name: BUTTON
  nameWithType: NitroxSettingsManager.SettingType.BUTTON
  fullName: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.BUTTON
  type: Field
  source:
    remote:
      path: NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
      branch: docfx
      repo: https://github.com/killzoms/Nitrox/
    id: BUTTON
    path: ../NitroxClient/GameLogic/Settings/NitroxSettingsManager.cs
    startLine: 129
  assemblies:
  - NitroxClient
  namespace: NitroxClient.GameLogic.Settings
  syntax:
    content: BUTTON = 3
    return:
      type: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
references:
- uid: NitroxClient.GameLogic.Settings
  commentId: N:NitroxClient.GameLogic.Settings
  href: NitroxClient.html
  name: NitroxClient.GameLogic.Settings
  nameWithType: NitroxClient.GameLogic.Settings
  fullName: NitroxClient.GameLogic.Settings
  spec.csharp:
  - uid: NitroxClient
    name: NitroxClient
    href: NitroxClient.html
  - name: .
  - uid: NitroxClient.GameLogic
    name: GameLogic
    href: NitroxClient.GameLogic.html
  - name: .
  - uid: NitroxClient.GameLogic.Settings
    name: Settings
    href: NitroxClient.GameLogic.Settings.html
  spec.vb:
  - uid: NitroxClient
    name: NitroxClient
    href: NitroxClient.html
  - name: .
  - uid: NitroxClient.GameLogic
    name: GameLogic
    href: NitroxClient.GameLogic.html
  - name: .
  - uid: NitroxClient.GameLogic.Settings
    name: Settings
    href: NitroxClient.GameLogic.Settings.html
- uid: System.Enum.NitroxModel.Extensions.GetAttribute``1
  commentId: M:NitroxModel.Extensions.GetAttribute``1(System.Enum)
  parent: NitroxModel.Extensions
  definition: NitroxModel.Extensions.GetAttribute``1(System.Enum)
  href: NitroxModel.Extensions.GetAttribute.html#NitroxModel_Extensions_GetAttribute__1_System_Enum_
  name: GetAttribute<TAttribute>(Enum)
  nameWithType: Extensions.GetAttribute<TAttribute>(Enum)
  fullName: NitroxModel.Extensions.GetAttribute<TAttribute>(System.Enum)
  nameWithType.vb: Extensions.GetAttribute(Of TAttribute)(Enum)
  fullName.vb: NitroxModel.Extensions.GetAttribute(Of TAttribute)(System.Enum)
  name.vb: GetAttribute(Of TAttribute)(Enum)
  spec.csharp:
  - uid: NitroxModel.Extensions.GetAttribute``1(System.Enum)
    name: GetAttribute
    href: NitroxModel.Extensions.GetAttribute.html#NitroxModel_Extensions_GetAttribute__1_System_Enum_
  - name: <
  - name: TAttribute
  - name: '>'
  - name: (
  - uid: System.Enum
    name: Enum
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.enum
  - name: )
  spec.vb:
  - uid: NitroxModel.Extensions.GetAttribute``1(System.Enum)
    name: GetAttribute
    href: NitroxModel.Extensions.GetAttribute.html#NitroxModel_Extensions_GetAttribute__1_System_Enum_
  - name: (
  - name: Of
  - name: " "
  - name: TAttribute
  - name: )
  - name: (
  - uid: System.Enum
    name: Enum
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.enum
  - name: )
- uid: NitroxModel.Extensions.GetAttribute``1(System.Enum)
  commentId: M:NitroxModel.Extensions.GetAttribute``1(System.Enum)
  isExternal: true
  href: NitroxModel.Extensions.GetAttribute.html#NitroxModel_Extensions_GetAttribute__1_System_Enum_
  name: GetAttribute<TAttribute>(Enum)
  nameWithType: Extensions.GetAttribute<TAttribute>(Enum)
  fullName: NitroxModel.Extensions.GetAttribute<TAttribute>(System.Enum)
  nameWithType.vb: Extensions.GetAttribute(Of TAttribute)(Enum)
  fullName.vb: NitroxModel.Extensions.GetAttribute(Of TAttribute)(System.Enum)
  name.vb: GetAttribute(Of TAttribute)(Enum)
  spec.csharp:
  - uid: NitroxModel.Extensions.GetAttribute``1(System.Enum)
    name: GetAttribute
    href: NitroxModel.Extensions.GetAttribute.html#NitroxModel_Extensions_GetAttribute__1_System_Enum_
  - name: <
  - name: TAttribute
  - name: '>'
  - name: (
  - uid: System.Enum
    name: Enum
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.enum
  - name: )
  spec.vb:
  - uid: NitroxModel.Extensions.GetAttribute``1(System.Enum)
    name: GetAttribute
    href: NitroxModel.Extensions.GetAttribute.html#NitroxModel_Extensions_GetAttribute__1_System_Enum_
  - name: (
  - name: Of
  - name: " "
  - name: TAttribute
  - name: )
  - name: (
  - uid: System.Enum
    name: Enum
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.enum
  - name: )
- uid: NitroxModel.Extensions
  commentId: T:NitroxModel.Extensions
  parent: NitroxModel
  href: NitroxModel.Extensions.html
  name: Extensions
  nameWithType: Extensions
  fullName: NitroxModel.Extensions
- uid: NitroxModel
  commentId: N:NitroxModel
  href: NitroxModel.html
  name: NitroxModel
  nameWithType: NitroxModel
  fullName: NitroxModel
- uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  commentId: T:NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  parent: NitroxClient.GameLogic.Settings
  href: NitroxClient.GameLogic.Settings.NitroxSettingsManager.html
  name: NitroxSettingsManager.SettingType
  nameWithType: NitroxSettingsManager.SettingType
  fullName: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
  spec.csharp:
  - uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager
    name: NitroxSettingsManager
    href: NitroxClient.GameLogic.Settings.NitroxSettingsManager.html
  - name: .
  - uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
    name: SettingType
    href: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.html
  spec.vb:
  - uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager
    name: NitroxSettingsManager
    href: NitroxClient.GameLogic.Settings.NitroxSettingsManager.html
  - name: .
  - uid: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType
    name: SettingType
    href: NitroxClient.GameLogic.Settings.NitroxSettingsManager.SettingType.html
memberLayout: SeparatePages
