using System;

namespace NitroxModel.DataStructures.GameLogic.Buildings.New;

public struct BuildPieceIdentifier : IEquatable<BuildPieceIdentifier>
{
    public NitroxTechType Recipe;
    public NitroxBaseFace? BaseFace;
    public NitroxInt3 BaseCell;
    public NitroxInt3 PiecePoint;

    public BuildPieceIdentifier(NitroxTechType recipe, NitroxBaseFace? baseFace, NitroxInt3 baseCell, NitroxInt3 piecePoint)
    {
        Recipe = recipe;
        BaseFace = baseFace;
        BaseCell = baseCell;
        PiecePoint = piecePoint;
    }

    public bool Equals(BuildPieceIdentifier other)
    {
        return Recipe.Name.Equals(other.Recipe.Name) && BaseFace.Equals(other.BaseFace) && BaseCell.Equals(other.BaseCell) && PiecePoint.Equals(other.PiecePoint);
    }

    public override bool Equals(object obj)
    {
        return obj is BuildPieceIdentifier buildPieceIdentifier && Equals(buildPieceIdentifier);
    }

    public static bool operator ==(BuildPieceIdentifier left, BuildPieceIdentifier right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(BuildPieceIdentifier left, BuildPieceIdentifier right)
    {
        return !(left == right);
    }

    public override string ToString()
    {
        return $"BuildPieceIdentifier [Recipe: {Recipe}, BaseFace: {BaseFace}, BaseCell: {BaseCell}, PiecePoint: {PiecePoint}]";
    }

    // Generated by Visual Studio
    public override int GetHashCode()
    {
        int hashCode = 920055407;
        hashCode = hashCode * -1521134295 + Recipe.GetHashCode();
        hashCode = hashCode * -1521134295 + BaseFace.GetHashCode();
        hashCode = hashCode * -1521134295 + BaseCell.GetHashCode();
        hashCode = hashCode * -1521134295 + PiecePoint.GetHashCode();
        return hashCode;
    }
}
