name: Building Master
on:
  push:
    branches:
      - master

jobs:
  setup:
    if: github.repository_owner == 'SubnauticaNitrox'
    runs-on: [self-hosted, linux]
    steps:
    - name: Checking out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

  build:
    needs: setup
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        configuration: [Debug, Release]
        runtime: [win-x64, win-arm64, linux-x64, linux-arm64, osx-x64, osx-arm64]
    steps:
    - name: Build
      run: dotnet build Nitrox.Launcher/Nitrox.Launcher.csproj -c ${{ matrix.configuration }} -r ${{ matrix.runtime }}

  test:
    needs: build
    runs-on: [self-hosted, linux]
    steps:
    - name: Run Tests
      continue-on-error: true
      run: dotnet test Nitrox.Test/Nitrox.Test.csproj --logger trx --results-directory "test_results"

    - name: Upload Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
      if: (!cancelled())
      with:
        files: |
          test_results/*.trx
