name: Test Pull Request
on:
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
    - name: Checking out repository
      uses: actions/checkout@v5

    - name: Run Tests
      run: dotnet test Nitrox.Test/Nitrox.Test.csproj --logger trx --results-directory "test_results"

    - name: Upload Event File
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: (!cancelled())
      with:
        name: Test Results
        path: |
          test_results/*.trx
